# Generated by Django 4.0.3 on 2022-03-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='credito',
            new_name='creditos',
        ),
    ]
